version: 0.2

phases:
  install:
    commands:
      - echo Installing system dependencies...
      - yum install -y python3 python3-pip
      - echo Creating virtual environment...
      - python3 -m venv .venv
      - . .venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
  pre_build:
    commands:
      - . .venv/bin/activate
      - echo Running pre-build steps...
      - pytest --version
  build:
    commands:
      - . .venv/bin/activate
      - echo Running tests...
      - pytest
  post_build:
    commands:
      - echo Build completed successfully.
artifacts:
  files:
    - '**/*'
